### ISSUE TITLE
게시글 Description 수정 기능으로 TDD 연습

### ISSUE THREAD

**Issue by zoooo-hs** [zoooo-hs/instagram-clone-be#2]
# 입력
- /post/{postId}/description
- body: {description: String}
# 응답
- 변경된 description이 담긴 Post JSON

# todo
- [x]  변경한 description으로 200 ok 반환
- [x]  다른 user는 수정하지 못함
- [x]  post service.updateDescription 테스트하기
- [x]  post service return new desc, changed id
- [x]  실제 db 변경 사항 확인하기
- [x]  save repository 테스트
- [x]  find by id 테스트

**Comment by zoooo-hs** [comment]
## Controller, Service TDD + Mocking
- https://github.com/zoooo-hs/instagram-clone-be/commit/11f60c982ff68f9e5ab19c282d8077f7364b350a

## issue
- PostEntity와 같이 UserEntity를 외래키로 갖는 경우 save를 어떻게 테스트해야할까. 조사 필요

**Comment by zoooo-hs** [comment]
# Repository Test Case
- https://github.com/zoooo-hs/instagram-clone-be/commit/99a22d0e25b48ac8ca2338affa4004bb01fcd396
